# Generated by Django 3.2.8 on 2021-10-28 22:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='biodata',
            name='nama',
        ),
    ]
